### ISSUE TITLE
go get in "Build it yourself" section of the README

### ISSUE THREAD

**Issue by PaperMountainStudio** [RasmusLindroth/tut#10]
Is there a specific reason `go get github.com/RasmusLindroth/tut/` isn't used in "Build it yourself" section of the README? I think it is much simpler - 1 command instead of a few.

**Comment by RasmusLindroth** [comment]
There isn't a good reason except that if you clone it you can choose to use `go build` instead of `go install`. I will add `go get` as an option in the README. Thank you for the feedback :)

**Comment by RasmusLindroth** [comment]
Fixed in 04bbba4ca7ddf503cf7a452d938a00f1bac436ad
