### ISSUE TITLE
Can't start tut static build 0.0.38 on Ubuntu 20.04 : `panic: interface conversion: interface {} is nil, not bool`

### ISSUE THREAD

**Issue by Lertsenem** [RasmusLindroth/tut#105]
Hello,

I'm on Ubuntu 20.04. I recently tried to upgrade from tut 0.0.33 amd64 static to 0.0.38 amd 64 static, but I can't start this new version without a crash occuring. I did not  change my configuration in any way.

```shell
$> tut
panic: interface conversion: interface {} is nil, not bool

goroutine 1 [running]:
main.showTootOptions(0xc0000616e0, 0xc0005fc000, 0x0)
        /home/rasmus/programming/go/tut/feed.go:124 +0x1c25
main.(*TimelineFeed).DrawToot(0xc0005141e0)
        /home/rasmus/programming/go/tut/feed.go:737 +0x65
main.(*StatusView).AddFeed(0xc000310070, {0x95d940, 0xc0005141e0})
        /home/rasmus/programming/go/tut/statusview.go:113 +0x126
main.(*UI).LoggedIn(0xc000074480)
        /home/rasmus/programming/go/tut/ui.go:493 +0x4a05
main.main()
        /home/rasmus/programming/go/tut/main.go:143 +0xeb0
$> echo $?
2
```

Did anyone encountered this issue? Am I missing something?

**Comment by RasmusLindroth** [comment]
Hi!

I looked around a bit and it seems like your instance of Mastodon runs version v2.6.5. And it doesn't support bookmarks. If that's true I suggest that you update your instance to a newer version as it quite old.

But I'll fix so it doesn't crash even if you're on an older version. Thank you for the bug report :)

**Comment by RasmusLindroth** [comment]
Now I've updated it. Could you please try the latest version to see if it works?

**Comment by Lertsenem** [comment]
Yes, it works now, thanks a lot !

Sorry, I forgot I was running an old unmaintained version. :/
I need to find time to update it.
