### ISSUE TITLE
AccessToken with password manager not working

### ISSUE THREAD

**Issue by DhruvaSambrani** [RasmusLindroth/tut#109]
AccessToken with '!CMD!' does not verify the account signin correctly and tut requires me to login again. When the accesstoken is written back to file directly, it works fine.

Not sure how to provide logs for the same

**Comment by RasmusLindroth** [comment]
It still works for me.

```Name = 'tut'
Server = 'https://fosstodon.org'
ClientID = 'hidden'
ClientSecret = '!CMD!gopass show -o -f misc/tut-secret'
AccessToken = '!CMD!gopass show -o -f misc/tut-token'
```

Could show me what command you're trying to run? And do you get the expected output when you run the command in your terminal? Just mask the parts of the command if it contains some private data and I'll test it out

**Comment by DhruvaSambrani** [comment]
I use pass, so `!CMD!pass show tut/accesstoken` is what I am using. When I run `tut`, the initial "Sign in to your mastodon instance" pops up. When I paste the output of the command into the config.ini and start tut again, it works fine, so the password in the psstore is ok.

ClientID and ClientSecret work fine. This is on 0.0.41, which I think is the latest

**Comment by RasmusLindroth** [comment]
I've tested it and the problem seems to have been that pass adds an newline to the output. I've updated tut to trim the output from the command, so test the latest version of tut and test if it works :)

**Comment by DhruvaSambrani** [comment]
It works now!! Thank you!
