### ISSUE TITLE
Can't compose

### ISSUE THREAD

**Issue by bananajoe-tweak** [RasmusLindroth/tut#112]
I'm trying to use the debian package of tut.
When I try the command :c  aka (compose), a window opens, but I can't write anything inside. I've tried to click with the mouse, or every keys of the keyboard, the tut terminal window seems to be non responsive.

**Comment by toxision** [comment]
I am not an expert.....
Tut is loading your default editor. And per default, usually at least one is installed on every system...I would assume. Have you tried enforcing a (default) editor via EDITOR=.... (vim, micro, nano etc...) in your shell .rc config?

Cheers,
Chris

**Comment by bananajoe-tweak** [comment]
This probably is something close to it. When I click in the window that appear after I hit :compose, the program kind a hangs, another window appears over it, and I kind a am able to write into it, but not much. It also kind a froze when I tried to look at the :favorites.

It's a nice client for scrolling through the toots, it's clean and readable. I like it very much. I wish you luck for the development of tut.

**Comment by bananajoe-tweak** [comment]
Could'nt enforce any editor, but you put me on the right track. There was no bug. I thought the program had frozen, but it was becaus I was  unaware the vim text editor was waiting for a command. I had to learn a little about vim, and now I can compose toots.

Thanx for making tut a reality,
