### ISSUE TITLE
Own toot editor

### ISSUE THREAD

**Issue by drequivalent** [RasmusLindroth/tut#120]
Using your system text editor for composing toots may be nice, but it lacks features like mention or emoji autocomplete.

**Comment by DhruvaSambrani** [comment]
This would be more useful as a lsp feature than a full fledged editor, don't you think?

**Comment by RasmusLindroth** [comment]
I agree with @DhruvaSambrani, a LSP server would fit this project better. I think a custom editor would be too difficult to manage as tview, the framework I'm using, is missing that feature right now. I may rethink this if and when it's added to this.

A LSP server is probably also quite difficult, but it seems more fun and likely something more people would use.

**Comment by RasmusLindroth** [comment]
This is available in the beta release :)
