### ISSUE TITLE
Use VIM with tut

### ISSUE THREAD

**Issue by suelectronico** [RasmusLindroth/tut#127]
Hi, iḿ searching in the config.ini to change my defaut text editor from vi to vim, but I can´t find nothing to do it.
Can you help me please.
Excuse me, I'm Spanish and my english is not so good.

Thanks

**Comment by RasmusLindroth** [comment]
Hola! :)

It's using your environmental variable `$EDITOR`, so you'll need to edit the config of your shell. Usually it's `.bashrc` 

You can set it like this

`export EDITOR='program'`

Don't forget to run `source .bashrc` or open a new terminal
