### ISSUE TITLE
token stored secured

### ISSUE THREAD

**Issue by r3k2** [RasmusLindroth/tut#13]
Hello, will tut allow me to run pass/gopass to fetch the token from the pass/gopass password manager like I do with other tools?
example:
```
AccessToken: `gopass show -o -f mastodon/myaccount@mydomain`
```
Thanks, I hope you add some ascii preview for images or something like gomuks does (gomuks is a matrix chat go client)

**Comment by RasmusLindroth** [comment]
Good features. I'll look at both of them, especially the one about storing the token more securely as it shouldn't be that hard.

I don't know how hard it would be to implement ascii preview, so I will see how gomuks does it.

Thank you for the suggestions :)

**Comment by r3k2** [comment]
@RasmusLindroth yeah is good to not have the token is a clear txt config, example: I want to save all my dot file on gitlab and is easy for someone to git add the config by mistake, to resolve this usually unix/linux CLI apps have the hability to parse other programs like "pass" or "gopass" so the password/token etc gets call as needed and never in clear mode at rest.

**Comment by RasmusLindroth** [comment]
Now this is implemented. Check the latest release. Thanks for the feedback :)
