### ISSUE TITLE
Disabling the notification feed breaks home timeline

### ISSUE THREAD

**Issue by stoerdebegga** [RasmusLindroth/tut#132]
There seems to be another strange issue in version 1.0.0.

**OS**: Fedora 36
Shell: zsh 5.8.1
**Terminal Emulator**: kitty
**Build**: tut-amd64-static

When disabling the notification feed via ```notification-feed=false``` the home timeline breaks in the way that you won't see any entries, but you can still navigate them.

I have tried this with a freshly created configuration file to which the only change was disabling the notification feed.

**Notification Feed Enabled:**

![notification-feed-true](https://user-images.githubusercontent.com/118527/167084141-98910a6f-5c01-4d9b-9e7a-a329efd6f64b.png)

**Notification Feed Disabled:**

![notification-feed-false](https://user-images.githubusercontent.com/118527/167084231-95403f09-c57b-4f0b-9410-213e92a35424.png)

**Comment by RasmusLindroth** [comment]
Thank you for the issue. It's fixed in the latest release :)
