### ISSUE TITLE
tut v1.0.2 fails to build on OpenBSD

### ISSUE THREAD

**Issue by russsharek** [RasmusLindroth/tut#134]
~/tut-1.0.2
$ go build
# github.com/RasmusLindroth/tut/feed
feed/feed.go:109:28: f.loadingNewer.mux.TryLock undefined (type sync.Mutex has no field or method TryLock)
feed/feed.go:127:28: f.loadingOlder.mux.TryLock undefined (type sync.Mutex has no field or method TryLock)

**Comment by RasmusLindroth** [comment]
I think you need to update your version of Go, because TryLock seems to have been introduced in version 1.18

**Comment by russsharek** [comment]
$ go version
go version go1.17.7 openbsd/amd64

Mystery solved. Thank you!
