### ISSUE TITLE
cant use :compose after one of the latest updates.

### ISSUE THREAD

**Issue by r3k2** [RasmusLindroth/tut#135]
Not sure which one, but for sure in the last 1-2 weeks. everytime I try to :compose I can't hit E anymore to Edit.
I am on a CMD prompt and only way to get out is with Esc and of course that closes the :compose what has change? do I need to do anything new? I have overread the new config and dont see anything breaking, I did turn off the msg I was getting before liking or retooting a post, it was super annoying lol not sure why is there :)

**Comment by toxision** [comment]
Can confirm, same issue here. Nevertheless to highlight that just pressing 'e' still works fine to create a new toot.

**Comment by r3k2** [comment]
@toxision not to me, if I type "e" it just get stdin to the CMD bar
here is a screenshot
![tut-issue](https://user-images.githubusercontent.com/5316229/167465275-d90f733b-de5d-46a7-ad24-b73cd8db069e.png)

**Comment by RasmusLindroth** [comment]
Good catch! I will try push a fix tomorrow. I found the issue, but don't have time to fix it now. In the meantime you'll have to use the key `C` instead :)

**Comment by RasmusLindroth** [comment]
Now there's a new release that solves the bug
