### ISSUE TITLE
Can not install and build on ubuntu

### ISSUE THREAD

**Issue by GeraldSoellinger** [RasmusLindroth/tut#138]
Hello!
I cloned the project and tried to build it, according to the instruction on the project page:

> # You can also clone the repo if you like
> # First clone this repository
> git clone https://github.com/RasmusLindroth/tut.git
> 
> # Go to that folder
> cd tut
> 
> # Build or install
> 
> # Install (usally /home/user/go/bin)
> go install
> 
> # Build (same directory i.e. ./ )
> go build

 but I get this error:

~/code/tut$ sudo go install
build github.com/RasmusLindroth/tut: cannot load embed: malformed module path "embed": missing dot in first path element
~/code/tut$ sudo go build
build github.com/RasmusLindroth/tut: cannot load embed: malformed module path "embed": missing dot in first path element

Do you have any idea what the problem is?

**Comment by GeraldSoellinger** [comment]
I also tried the simpler command and get this error:

~$ sudo go get -u github.com/RasmusLindroth/tut
package embed: unrecognized import path "embed" (import path does not begin with hostname)

**Comment by RasmusLindroth** [comment]
What version of Go do you run? I think the embed feature got added in a recent version.

https://www.cyberciti.biz/faq/how-to-install-gol-ang-on-ubuntu-linux/

**Comment by RasmusLindroth** [comment]
I looked and I think this project requires 1.17 or 1.18, so you will have to download Go outside of the repos Ubuntu provides. Maybe this guide can help

https://github.com/golang/go/wiki/Ubuntu

**Comment by RasmusLindroth** [comment]
You can also download pre-built binaries here 

https://github.com/RasmusLindroth/tut/releases

You probably want tut-amd64

**Comment by GeraldSoellinger** [comment]
I tried to use the binary build, but I can not execute the binary. Although I applied chmod +x

**Comment by RasmusLindroth** [comment]
Weird, do you get an error?

Test adding this repo, even if it says Debian it should work. I've tried it myself in the past

http://packages.azlux.fr/

**Comment by GeraldSoellinger** [comment]
> 



> I looked and I think this project requires 1.17 or 1.18, so you will have to download Go outside of the repos Ubuntu provides. Maybe this guide can help
> 
> https://github.com/golang/go/wiki/Ubuntu

I followed this instruction, and now it works with go version go1.18.1 linux/amd64!

Thank you very much!:)
