### ISSUE TITLE
Feature Request - Ability to set post visibility.

### ISSUE THREAD

**Issue by linuxclowns** [RasmusLindroth/tut#14]
Would be nice to have the option to set a post/reply's visibility.

For example, public, followers only, unlisted, etc.

**Comment by RasmusLindroth** [comment]
Now I've implemented it, but I'll need to fire up my local mastodon server to test it and it's on another computer. So a new release will come tomorrow.

Thank you for the issue :)

**Comment by linuxclowns** [comment]
Happy to help, and looking forward to the new features!

**Comment by RasmusLindroth** [comment]
Fixed in e8dca42c5c940fe5decbcb65060726926afdd527
