### ISSUE TITLE
Thoughts: extending leader-action bindings for tags

### ISSUE THREAD

**Issue by toxision** [RasmusLindroth/tut#141]
I know the leader-action feature has just moved into tut. However I am already looking for some sort of additional value. Currently tut does not support adding additional tabs into the UI for i.e. frequently used tags.
So it would be awesome to do that via a leader-action. Something like that I have in mind:
leader-action=tag tut,tt
leader-action=tag linux,tl
etc....

This would make browsing through tags more convenient 🥰

**Comment by RasmusLindroth** [comment]
Added in the latest version. Thank you for the suggestion :)
