### ISSUE TITLE
Line breaks in the middle of words

### ISSUE THREAD

**Issue by brunofontes** [RasmusLindroth/tut#142]
Hello,

Not sure if I am doing something wrong or not as I do not remember this before. But I recently started noticing the display toot line breaks are really hard, breaking words in the middle.

Is that a possible bug? Or am I doing something wrong here?

![screenshot_5](https://user-images.githubusercontent.com/15826395/167956956-373f0684-a2e4-45d9-a055-95d5159f074a.png)

Thank you so much in advance!
Bruno

**Comment by RasmusLindroth** [comment]
Thank you for the bug report. It's fixed in the latest release :)

**Comment by brunofontes** [comment]
Thank you so much, Rasmus! It is working perfectly now! :)
