### ISSUE TITLE
Editor vis does not work

### ISSUE THREAD

**Issue by ithuriel-github** [RasmusLindroth/tut#144]
I have only used tut with busybox's vi and martanne's [vis](https://github.com/martanne/vis).

When using vis after saving and quitting out of a file the compose window doesn't contain the file's contents

The only difference that I can see between the two editors is the file path used. On my system /tmp is a symlink to /run/tmp. Vis uses the /run/tmp path and vi the /tmp

**Comment by RasmusLindroth** [comment]
I think the latest release fixes it. Please reopen this if it's still a problem. 

Thank you for the bug report :)

**Comment by m040601** [comment]
Yeah, I "think", I am experiencing a similar problem with nvim.
I always get a "read only" file created in "/tmp"

````
$ echo $EDITOR
/usr/bin/nvim
````

Start tut. Hit 'c' compose. Hit 'e' edit. I get this:

````
0/1)tut885954209    [RO]  [-]               text  utf-8[unix][tab 8]  All
"/tmp/tut885954209" [readonly] --No lines in buffer--
````
