### ISSUE TITLE
accounts.toml getting corrupt all the time

### ISSUE THREAD

**Issue by nyex** [RasmusLindroth/tut#145]
I am not sure how to even explain this one. I sync my tut config files between computers with syncthing, so I'm not sure if this could be related, but that's not something that should be happening _because_ of syncthing, I think (I mean, I sync a lot of things with it, it only creates chaos every once in a while).

Since the last few weeks (I'd say last two or three updates, but I didn't use tut for a while so I'm not sure) my accounts.toml file seems to get corrupted quite often; when I try to open tut using --user, sometimes it opens, but then the next time I try to open it, it fails, and when I check the accounts file it completely ate the whole of one account info (I have 2 accounts) and replaced it with 3 random characters (I am sorry I deleted it already, but it was something like %3w or some nonsense). So I deleted the extra characters and did the process to add a new account. All worked again.

Earlier today I went to add a new account and it went into a loop asking for the instance, then the auth code, then the instance again etc etc. When I opened the accounts.toml file, it was corrupted again, and there was only two instances (the new one and one of the others). The third bit of info had been replaced by random characters again. When I deleted those, I could access the new account (despite the loop that had happened before).

I can help test to figure out what's going on, but I have no idea how to go about it :)

**Comment by RasmusLindroth** [comment]
I think the latest release fixes it. Please reopen this if it's still a problem. 

Thank you for the bug report :)
