### ISSUE TITLE
Feature request: setting default post visibility

### ISSUE THREAD

**Issue by nyex** [RasmusLindroth/tut#146]
Hey!

It would be nice if we could set the default post visibility for toots. I prefer to post 'unlisted' instead of 'public', for instance. Having it pre-defined (maybe in the config file?) would make things a lot easier :)

**Comment by RasmusLindroth** [comment]
Good idea!

I found that you can set this as an account setting, so it's an easy fix. But I think I will add so you can set these preference inside of the application, so you don't have to open the browser. So you can expect this in the next release :)

**Comment by nyex** [comment]
Hm, I do have it set in the account settings to post as "unlisted" by default, and tut still posts everything as "public" by default, so maybe it's a case of it not following the account settings? (Or not yet? Did you mean you will have the app follow the account settings in the next release? Either way, sounds great 👍🏽 )

**Comment by RasmusLindroth** [comment]
Now it's all implemented. Check out `:preferences`. Thank you for the suggestion :)
