### ISSUE TITLE
Feature request: Media alt-text

### ISSUE THREAD

**Issue by avalonw** [RasmusLindroth/tut#15]
Would it be possible to list the alt text from an image (when it exists) under the image link? It'd be a convenient way to judge whether the image is one I want to actually see.

**Comment by RasmusLindroth** [comment]
Great idea!

I will also try to make it possible to add a description to your attachments when you upload them, but it seems like go-mastodon needs an update before it's possible https://github.com/mattn/go-mastodon/issues/129

**Comment by RasmusLindroth** [comment]
Fixed in c8fd68c4010b69b272bba9ff1e0423444545029f, thank you for the issue
