### ISSUE TITLE
tut won't read ~/.config/tut/themes/dracula.ini

### ISSUE THREAD

**Issue by kars0n777** [RasmusLindroth/tut#153]
I made a dracula theme for tut and followed the example themes from the repo, but when I put my theme as `theme=dracula` in my config.ini it says dracula theme not found. 

When I put in `theme=nord` the theme changes but as soon as I put a theme that doesn't come with tut it fails to launch.

**Comment by kars0n777** [comment]
My ~/.config/tut/ directory looks like this, just like the example config in the repo 

```
~/.config/tut ❯ tree
.
├── accounts.toml
├── config.ini
└── themes
    └── dracula.ini
```

**Comment by kars0n777** [comment]
My config folder looks likes this just like the example config, (don't mind the accidental close of issue, new to github lol)
```
~/.config/tut ❯ tree
.
├── accounts.toml
├── config.ini
└── themes
    └── dracula.ini
```

**Comment by RasmusLindroth** [comment]
Now tut supports local themes in `~/.config/tut/themes/dracula.ini` :)
