### ISSUE TITLE
Is there a refresh/reload button?

### ISSUE THREAD

**Issue by Ashdemai** [RasmusLindroth/tut#154]
It would be really useful instead of having to exit and loading the program to get a fresh set of posts. Close this issue if it's dumb, I was just wondering, because there's nothing in the config or the wiki about this.

**Comment by RasmusLindroth** [comment]
You can't do that, but I could add that functionality. But it shouldn't be required as tut should load new posts automatically. Do you have an issue with new posts not showing up?

**Comment by Ashdemai** [comment]
> Do you have an issue with new posts not showing up?
Yeah, it doesn't seem to get updated at all. I have to manually type `:timeline home` and then it grabs the latest posts.

If it's easy I wouldn't mind a refresh button.

**Comment by RasmusLindroth** [comment]
Now you should be able to force load new toots with `:newer` or by setting a `leader-action` with `newer` as an action :)
