### ISSUE TITLE
Feature request: set window title

### ISSUE THREAD

**Issue by daveriedstra** [RasmusLindroth/tut#158]
This is definitely a nice-to-have, but is it possible for tut to set the terminal window title, like `nnn` or `nvim` (with `set title`)?

Here are three terminals in a tabbed layout, from left to right it's tut, nnn, and nvim:

![Three terminal tabs titled "bash" (tut), "~/Documents" (nnn), and "triage.md" (nvim)](https://user-images.githubusercontent.com/3504098/179849532-23a4da83-66df-4f28-b30f-2a72063981f4.png 'Three terminal tabs titled "bash" (tut), "~/Documents" (nnn), and "triage.md" (nvim)')

Thanks for tut!

**Comment by daveriedstra** [comment]
Oh interesting. What terminal are you using? I'm using kitty in that screenshot, but I just tested gnome-terminal, rxvt, and foot and they're all the same.

**Comment by RasmusLindroth** [comment]
My mistake, it's not the terminal but zsh shell that updates the title automatically. If I run bash in my terminal I get the same result as you

**Comment by RasmusLindroth** [comment]
It's now shipped with the latest release

**Comment by Ashdemai** [comment]
My man Rasmus with the quick fixes!

**Comment by daveriedstra** [comment]
Amazing, thank you Rasmus! (Also, a point in favour of zsh...)
