### ISSUE TITLE
Own theme don't work

### ISSUE THREAD

**Issue by nerdbude** [RasmusLindroth/tut#162]
Hello, 
I try to apply my own theme to tut (https://github.com/nerdbude/Cyber23). 

- I change my `config.ini` to `themes=none` and put the colors below this line (does not work)
- I create a cyber23.ini file in `~/.config/tut/themes/` and tut give me the message "could not find theme cyber23" 

any ideas or fixes?

**Comment by RasmusLindroth** [comment]
What version of tut are you running? You can get it with `tut -v`.And could you post the content of `cyber23.ini` here, then I can test it on my computer.

But it seems tut doesn't pick up your config directory. 
The config directory tut should be located in `$XDG_CONFIG_HOME` if it's set or in `$HOME/.config` if it's not set.

**Comment by nerdbude** [comment]
ver. 0.0.46 

The content of the cyber23.ini: 

```
background=#1c1c1c
text=#dadada
subtle=#0087ff
warning-text=#ff005f
text-special-one=#afd787
text-special-two=#afd75f
top-bar-background=#ff005f
top-bar-text=#1c1c1c
status-bar-background=#ff005f
status-bar-text=#1c1c1c
status-bar-view-background=#ff005f
status-bar-view-text=#1c1c1c
list-selected-background=#ff0087
list-selected-text=#f8f8f2
list-selected-inactive-background=#d75fd7
list-selected-inactive-text=#e4e4e4
controls-text=#e4e4e4
controls-highlight=#afd75f
autocomplete-background=#080808
autocomplete-text=#e4e4e4
autocomplete-selected-background=#d75fd7
autocomplete-selected-text=#e4e4e4
button-color-one=#ff0087
button-color-two=#080808
timeline-name-background=#080808
timeline-name-text=#808080
```

I tried the nord.ini within my `.config` and it works

**Comment by RasmusLindroth** [comment]
Version 0.0.46 doesn't support themes in `~/.config/tut/themes`, you'll need at least version 1.0.12. Try and download a newer version over at https://github.com/RasmusLindroth/tut/releases

If you don't want to install it manually try to ask the maintainer of the package on your distro to make an update as 0.0.46 got released over a year ago

**Comment by nerdbude** [comment]
oh ok :D 
thanks for the answers
