### ISSUE TITLE
Fails to create ~/.config/tut if ~/.config doesn't already exist

### ISSUE THREAD

**Issue by sjmulder** [RasmusLindroth/tut#169]
tut yields an error when the `~/.config` directory doesn't yet exist:

    $ file ~/.config
    /home/sjmulder/.config: cannot open `/home/sjmulder/.config' (No such file or directory)
    
    $ tut
    2022/11/08 23:25:50 couldn't create dirs. Error: mkdir /home/sjmulder/.config/tut: no such file or directory
    
    $ mkdir ~/.config
    
    $ tut
    You will have to log in to your Mastodon instance to be able
    to use Tut. The default protocol is https:// so you won't need
    ...

It should probably create it automatically.

**Comment by RasmusLindroth** [comment]
Thank you for finding the bug. A fix will land in the next release, which I hope won't be that far away

**Comment by RasmusLindroth** [comment]
It's fixed in release 1.0.18
