### ISSUE TITLE
Feature Request: set toot language

### ISSUE THREAD

**Issue by sophiabrandt** [RasmusLindroth/tut#171]
The vanilla web client allows you to change the language of a toot.

By default, the language is specified in your profile as your "toot language" but you can choose to select a different language for individual toots.

As someone switching between different languages on the same user account, I find this feature quite important (for my use case of Mastodon).

**Comment by RasmusLindroth** [comment]
Good suggestion. I'll add it to tut soon :)

**Comment by RasmusLindroth** [comment]
Now you can change the language :)

**Comment by sophiabrandt** [comment]
Wow, thanks so much. 😍
