### ISSUE TITLE
Feature request: Filtering boosts from timelines

### ISSUE THREAD

**Issue by debdrup** [RasmusLindroth/tut#174]
One option found in the webUI but not found in any Mastodon client that I know of, is the ability to filter boosts from timelines.

In case it's not immediately apparent why this is an option, the best way I can summarize it is by making the point that boosts don't require hardly any effort to share, so people tend to use them liberally. Contrast this with people sharing something they _really_ care about, in which case they'll usually take the time to write a little bit about it when including it in a tweet.

So I'd like to ask that an option gets added to be able to filter out boosts in one or more timelines; it makes sense to me to add this as a boolean to the timelines property in the config.ini file, so instead of writing `timelines=timeline,Name,'letter'`, you'd write `timelines=timeline,Name,'letter',false` to not display toots (as it should probably default to being on if not specified).
This way, it'd also be possible to add a timeline called boosts, in case there's someone who wants to keep them as a separate timeline.

**Comment by HelmicNewciv** [comment]
This is exactly what I was looking for - people boost a lot of stuff, and while I like seeing them, I want to be able to see what the people I'm following are themselves posting without it getting buried.  Same for filtering followed tags and whatnot, having some granularity to put things in different feeds would be very handy.

**Comment by RasmusLindroth** [comment]
This will land in the next release and I'm almost done with this feature :)

**Comment by RasmusLindroth** [comment]
Now it's included in the latest release. The syntax is like you proposed with the addition of replies.

 `timelines=feed,[name],[keys...],[showBoosts],[showReplies]`
 
 Thank you for the suggestion!

**Comment by HelmicNewciv** [comment]
Would there be a way to have a timeline be ONLY the boosts and/or replies?  For me I'm wanting to split my home timeline  into two parts, one with regular posts and replies and then another that's just boosts, so that I still see the boosts but they can't bury the original posts.

**Comment by RasmusLindroth** [comment]
> Would there be a way to have a timeline be ONLY the boosts and/or replies? 

See the latest release. You now have `special` in timelines and toggle boosts and/or replies with `true/false`. As a leader and a command you now have `special-all`, `special-boosts` and `special-replies` :)
