### ISSUE TITLE
Editor error exit should not kill tut

### ISSUE THREAD

**Issue by larsks** [RasmusLindroth/tut#178]
If your editor exits with an error code (maybe you goofed your editor configuration), it has the unfortunate side effect of killing Tut. It would be more pleasant if Tut would simply report an error and continue running (ideally returning the the Post/Edit/... menu).

**Comment by RasmusLindroth** [comment]
I think the latest release should fix this issue. Thank you for the issue

**Comment by larsks** [comment]
Looks good. Thanks!
