### ISSUE TITLE
:user search not finding accounts

### ISSUE THREAD

**Issue by ryspace** [RasmusLindroth/tut#180]
I've had this issue multiple times over the past few days, and I don't know of a way to debug or get any logs to help you troubleshoot it, but:

using the `:user @username@instance.tld` search is frequently (but not always) not yielding results. The accounts do exist, and I'm able to find them in a browser by navigating to the profile or by using the search feature in a web client.

Any tips as to how I can help you figure out how to fix this?

**Comment by RasmusLindroth** [comment]
I think the latest version of tut should fix this :)
