### ISSUE TITLE
tut stops when lynx doesn't end correctly

### ISSUE THREAD

**Issue by Glog78** [RasmusLindroth/tut#181]
ok i have configured tut to open url's with lynx. There are rare cases when lynx not end's gracefully. In this case tut end's to.

Example:

config.ini 
link-viewer=lynx

try to open a toot with https://www.washingtonpost.com/ in it.

Example output:

tut

Looking up www.washingtonpost.com
Making HTTPS connection to www.washingtonpost.com
SSL callback:ok, preverify_ok=1, ssl_okay=0
SSL callback:ok, preverify_ok=1, ssl_okay=0
SSL callback:ok, preverify_ok=1, ssl_okay=0
Verified connection to www.washingtonpost.com (cert=www.washingtonpost.com)
Certificate issued by: /C=US/O=Entrust, Inc./OU=See www.entrust.net\/legal-terms/OU=(c) 2014 Entrust, Inc. - for authorized use only/CN=Entrust Certification Authority - L1M
Secure 256-bit TLSv1.3 (TLS_AES_256_GCM_SHA384) HTTP connection
Sending HTTP request.
HTTP request sent; waiting for response.
HTTP/1.0 302 Moved Temporarily
Data transfer complete
HTTP/1.0 302 Moved Temporarily

lynx: Start file could not be found or is not text/html or text/plain
      Exiting...
2022/11/21 00:52:09 exit status 1

**Comment by RasmusLindroth** [comment]
Thank you for the issue. I've created a fix that will land in the next release of tut. If you want it now you can use the branch 1.0.20 :)

**Comment by Glog78** [comment]
fixed thank you :) just tested
