### ISSUE TITLE
No Issue: Just a big thank you and praise for this tool (release 1.0.20)

### ISSUE THREAD

**Issue by m040601** [RasmusLindroth/tut#185]
Yeap, that's it, I'm not reporting a bug or problem 

I just opened this issue to let you know how much I am appreciating this fantastic tool and where it is going.

Thank you also for maintainig the AUR packages for Archlinux. And the "tut-bin" packages for arm. Soooo useful for using it with the Raspberry pi.

I've been using it since day one and following its development.
Each new release brings a little bit something, small, important and relevant.

Sometimes I feel like opening an issue, to request this or that missing feature. But then I pause for a minute and dont do that. And then a couple of weeks months later, just like magic, as if you had guessed the end user wishes, that feature gets added. Clearly the work of someone who understands how to properly design a text user interface.

Well you did it again:

> 
>     You can now follow and unfollow tags with :follow-tag tut and :unfollow-tag tut.
>     You can now add and remove users from lists. 
> 

Sooooo great !!!  One more thing that I can do in a text terminal to admin my mastodon account, instead of having to open and close my bloated web browser .

Small question: I can follow/unfollow tags. But is there a way to "list" the tags I am already "following" ? I sometimes forget wich tags I am following. I then go to my ":profile" and ":following" but this only seems to list the "@user@account" I am following, not the "tags". Am I correct ?

Oohh, by the way, another small question.
My only other possible wish or feature request for the future would be the ability to switch the mastodon account, without having to close and reopen tut.
Or am I missing something and the  the "correct" way, is to just open two or more different instances of tut each one logged in to  a different account ? Are there any "concurrency" or other issues of running many simultaneous instances this way ?

So anyway. Thank you and keep up the  good work.
No bloat, a very well thought ergonomy and usablility. A sane and well documented configuration file with examples.

As a command line fanatic, I am constantly testing and trying new ones.  See lot of  new tools, like,  "Hey look at my new  tool XYZ, it's written in Rust" or "Cool replacement for FOO written in Go".

But yours really stands out.

Ohhh ... and I never had it lock, freeze or crash. And I'm using it on a 14 year old computer :-)

**Comment by RasmusLindroth** [comment]
Thank you for all the kind words, I appreciate it :)
 
> Sometimes I feel like opening an issue, to request this or that missing feature. But then I pause for a minute and dont do that. 

Just go ahead and make an issue, I don't mind. Even if I don't implement it or don't have the time to do it I like new feature requests. It gives me ideas for what people think is missing.


> Small question: I can follow/unfollow tags. But is there a way to "list" the tags I am already "following" ? I sometimes forget wich tags I am following. I then go to my ":profile" and ":following" but this only seems to list the "@user@account" I am following, not the "tags". Am I correct ?

You are correct. But I can see now that you can get a list of tags that you're following, so I'll add this to tut. This should be an easy fix, so expect it to land in the next release.

I paste a link to the API as a reminder to myself.
https://docs.joinmastodon.org/methods/followed_tags/

> Oohh, by the way, another small question. My only other possible wish or feature request for the future would be the ability to switch the mastodon account, without having to close and reopen tut. Or am I missing something and the the "correct" way, is to just open two or more different instances of tut each one logged in to a different account ? Are there any "concurrency" or other issues of running many simultaneous instances this way ?

Currently you can't switch accounts when you are logged in, but that's a feature I would like to implement. And as for the second question, there's no problem with having multiple instances of tut open simultaneously. You can even be logged in to the same account with more than one client and it works. The only downside is that you'll get double notifications if you have enabled them.

And I'll leave this issue open as it contains feature requests.

Thanks again!

**Comment by omnivagant** [comment]
I just want to chime in, I'm very happy with this client, not least since I spent some time configuring the colors I wanted. Here is my current theme:
```ini
background=xrdb:background
text=#dfbf8e
subtle=#8a3324
warning-text=#f02323
text-special-one=#ffb000
text-special-two=#7cfc00
top-bar-background=background
top-bar-text=#7cfc00
status-bar-background=#ff6700
status-bar-text=#2b2b2b
status-bar-view-background=#a6e22e
status-bar-view-text=#2b2b2b
command-text=#ffb000
list-selected-background=#ff6700
list-selected-text=#2b2b2b
list-selected-inactive-background=background
list-selected-inactive-text=#ffb000
controls-text=#ffb000
controls-highlight=#a6e22e
autocomplete-background=background
autocomplete-text=#ffb000
autocomplete-selected-background=#ff6700
autocomplete-selected-text=#2b2b2b
button-color-one=#a6e22e
button-color-two=#272822
timeline-name-background=#272822
timeline-name-text=#7cfc00
```
on a semi transparent dark background.

**Comment by RasmusLindroth** [comment]
You can now login to multiple accounts in the same window :)
