### ISSUE TITLE
Pressing view, uh, locks me into view mode?

### ISSUE THREAD

**Issue by Moult** [RasmusLindroth/tut#19]
Once i press "V" to enter view mode, how do I exit it?

**Comment by RasmusLindroth** [comment]
You press Q or Escape. I'll write a better description about it in the README

**Comment by Moult** [comment]
@RasmusLindroth oh yes. Escape. Whoops! Thanks!

"Q", however, just goes back to the previous timeline / content.

**Comment by RasmusLindroth** [comment]
> "Q", however, just goes back to the previous timeline / content.

I think it's more logical if `Q` exists the view mode, so good catch. I'll fix it :)
