### ISSUE TITLE
[Enhancement?] Option to specify a certain config file

### ISSUE THREAD

**Issue by toxision** [RasmusLindroth/tut#195]
Hi there
Very often CLI/TUI tools allow to point to a certain config file in case the default one or even the path isn't in place.
Usually this is done with a -c/-C or --config flag. I really would like to see that as well for the tut client.
By that you could play with new features without touching your 'productive' config. Or it would enable one to have several layouts/stylings etc.. saved and applied whenever needed.
Just an idea....

Best regards,
Chris

**Comment by RasmusLindroth** [comment]
Now you can use `--config` to load `config.ini` from somewhere else and `--config-dir` if you want a completely different directory.  You can also set `TUT_CONF`  and `TUT_CON_DIR` as environment variables :)
