### ISSUE TITLE
OMG OMG <3 U

### ISSUE THREAD

**Issue by ReK2Fernandez** [RasmusLindroth/tut#2]
been using toot for some time... but GO and TUI! this is great! about to try it, please add auto reload. toot is missing that

**Comment by RasmusLindroth** [comment]
Thank you :)
It's on my to do list and should be an easy fix. I will have plenty of time week, so then I probably will have a new release

**Comment by ReK2Fernandez** [comment]
Hello, I was able to compile and run,  and notice Boost is not working? or did I mist configuring something? thanks <3

**Comment by RasmusLindroth** [comment]
I think boosts were working, but the UI didn't update. I've relased a new version with some more fixes, including an update of the UI if you boos a toot. Can you check it out and see if it's working now?

**Comment by ReK2Fernandez** [comment]
@RasmusLindroth sure I will try it and let you know later. thanks

**Comment by RasmusLindroth** [comment]
Thank you!
It should make a request to load newer feed items when you are on the top 4 toots in your feed, but I can have made some mistake.
I will add an timer during my next release so it checks for new toots without the user having to browse the list. I'm on vacation this week, so the new release should come pretty soon :)

**Comment by ReK2Fernandez** [comment]
@RasmusLindroth thanks! cant wait. "It should make a request to load newer feed items when you are on the top 4 toots in your feed"  is not... :/

**Comment by RasmusLindroth** [comment]
Now I found the bug, so hopefully it will work now. I've updated the release :)

**Comment by ReK2Fernandez** [comment]
@RasmusLindroth  awesome seems to be working now.!
