### ISSUE TITLE
Error: no key named Un[F]ollow

### ISSUE THREAD

**Issue by nikolay** [RasmusLindroth/tut#204]
I keep getting the following error when logging into [hachyderm.io](https://hachyderm.io):

```
$ tut
error parsing config for key tag-follow. Error: no key named Un[F]ollow
```

**Comment by RasmusLindroth** [comment]
The line in your config.ini (~/.config/tut/config.ini) should be like [this line](https://github.com/RasmusLindroth/tut/blob/4c9caea97a70319384af9250958a4978129c43ec/config.example.ini#L676).

If that doesn't work, could you send me your config.ini?

**Comment by nikolay** [comment]
@RasmusLindroth No such file exists. I created the example config, moved it in there, made sure that line exists, but it still is giving me the same error. I'm on macOS, by the way.

**Comment by nikolay** [comment]
@RasmusLindroth Also, every time I run tut, it starts XQuartz.

**Comment by HyperSuperMetaCtrl** [comment]
I'm running arch and installed the package from the aur and am also trying to join hachyderm.io.
I checked the config.ini and the the line you referenced is the same in my file. I still get this error. 
```
tut --version 
tut version 1.0.23 
https://github.com/RasmusLindroth/tut
```

**Comment by nikolay** [comment]
@RasmusLindroth It's the same situation with `~/Library/Application Support/tut/config.ini`- that line exists in there. Here's the version output:

```
$ tut --version
tut version 1.0.23
https://github.com/RasmusLindroth/tut
```

**Comment by RasmusLindroth** [comment]
I see the mistake. I'll make a new release that fixes this.

In the meantime you can delete the line `tag-follow="[F]ollow","Un[F]ollow",'f','F'` from your config and it should work

**Comment by HyperSuperMetaCtrl** [comment]
Can confirm it works like this. Thank you for the your quick response.

**Comment by RasmusLindroth** [comment]
Thank you for reporting this bug. Not a good start for new users, but I hope you'll like tut anyway,

It's fixed now :)
