### ISSUE TITLE
Theming command text

### ISSUE THREAD

**Issue by SlidingHorn** [RasmusLindroth/tut#208]
I'm making a custom theme for tut, and the one thing I need to theme individually that I can't seem to is the actual command text itself (not the autocomplete).

Currently it seems to take on one of either `top-bar-text`, `status-bar-text`, or `status-bar-view-text`, which, in my darker theme, causes the text to be illegible:

![screenshot-20221206163914](https://user-images.githubusercontent.com/6623121/206028987-df3cf799-3cf1-4a8f-88d6-e6067d95ada4.png)

Any chance of getting this particular item to have its own style?

**Comment by benjaminbhollon** [comment]
Yes, I was encountering this too when trying to port my beloved Everforest Light. I ended up having to settle for some color decisions I wasn't originally wanting to make it work.

**Comment by RasmusLindroth** [comment]
Now it's included in the latest version. Thank you for the issue and PR :)
