### ISSUE TITLE
Configuration option for styling selected toots in unfocused timelines

### ISSUE THREAD

**Issue by benjaminbhollon** [RasmusLindroth/tut#215]
While `list-selected-background/text` exists, the selected toots from timelines that aren't currently in focus seem to borrow their background and text colors from `status-bar-view-background/text`. Would it be possible for this to have its own configuration option? Probably `list-selected-unfocused-background/text` or `list-unfocused-background/text`

Thanks!

**Comment by benjaminbhollon** [comment]
Never mind, I looked at the default theme and saw a bunch of options that weren't documented in the default config file, which should cover this. (`list-selected-inactive-background/text`)

**Comment by RasmusLindroth** [comment]
You have this site if you want to test your themes. It doesn't have command-text, but every other option should be there :)

https://tut.anv.nu/theme

**Comment by benjaminbhollon** [comment]
Handy!

While I've got your attention, how open are you to accepting PRs with new themes? I'd be willing to try and port some popular color schemes over; I've already been porting my own preferred Everforest Light Hard.

**Comment by RasmusLindroth** [comment]
It would be awesome with more themes

**Comment by benjaminbhollon** [comment]
I'll consider working on that over break, then! The base16 theme standard for terminal themes should be fairly easy to convert once I figure out which items look good where. I'm getting close to perfecting Everforest Light, at which point it should be easy to do Dark.

How do you feel about multiple variants of the same theme? I assume having both the light and dark variant is okay, but many themes (like Everforest) also have versions with different levels of contrast. Should I port all of them or just a specific level of contrast?

**Comment by benjaminbhollon** [comment]
Gruvbox is seeming pretty easy to port so far. :)
![image](https://user-images.githubusercontent.com/33023252/207547804-c2937bf3-b2bc-4294-8324-fc12a863c6bc.png)
![image](https://user-images.githubusercontent.com/33023252/207549514-30015d9b-14f0-426d-b2f5-7a38747c23a3.png)
Still some kinks to iron out before I create a PR, though.
