### ISSUE TITLE
Enhancement - Hotkey for stick-to-top

### ISSUE THREAD

**Issue by Glog78** [RasmusLindroth/tut#216]
I love the new stick-to-top flag, but now if you stay on some other toot and have one incoming it switches even if you just reading the toot you had open. 
The most simple idea i had is to define a global hotkey ... (for me maybe <leader><t>)  to toogle stick to top

The other possibility with more comfort might be a timer based solution.
tut (user interaction happens) -> disable stick to top -> start or rest timer (time defined in conf compareable to leader timeout) -> enable stick to top

and thank you alot i love this feature already now ;)

**Comment by RasmusLindroth** [comment]
You can now use the command `:stick-to-top` or set it as a leader with `stick-to-top`. Thank you for the suggestion!
