### ISSUE TITLE
[wish] Only some notifications

### ISSUE THREAD

**Issue by flashymittens** [RasmusLindroth/tut#220]
Please provide an option to only show some notifications for Notifications timeline.

For example, I'd like to hide notification items that say that my post was boosted (or favorited) as it is too distracting.

**Comment by ryspace** [comment]
You can set this in your `config.ini`.  From the `config.example.ini`:

```
[desktop-notification]
# Notification when someone follows you.
# default=false
followers=false

# Notification when someone favorites one of your toots.
# default=false
favorite=false

# Notification when someone mentions you.
# default=false
mention=false

# Notification when someone edits their toot.
# default=false
update=false

# Notification when someone boosts one of your toots.
# default=false
boost=false

# Notification of poll results.
# default=false
poll=false

# Notification when there is new posts in current timeline.
# default=false
posts=false
```

**Comment by ryspace** [comment]
So I have an *idea* how this could be done, but I feel like I'd do it incredibly sloppily, and I'm not sure this is even something @RasmusLindroth would be interested in adding to tut, so I'll wait til they reply and see...

**Comment by RasmusLindroth** [comment]
Good suggestion. It will require a fix to go-mastodon that tut uses, but the API has support for it so it should be quite easy to implement.

**Comment by RasmusLindroth** [comment]
It's now included in the latest release, see `notifications-to-hide` under `[general]`
