### ISSUE TITLE
Add an option to switch booster with boosted user in TL

### ISSUE THREAD

**Issue by Lertsenem** [RasmusLindroth/tut#223]
In the TL view, when seeing a boost, I'm usually much more interested in seeing the handle of the person being boosted, rather than of the person boosting the toot.

I'd like a config option to allow that, maybe with an adaptation in the toot view to show somewhere "*boosted by @user@example.com*"

**Comment by RasmusLindroth** [comment]
Under `[general]` you now have `show-boosted-user` that will show the name of the person who made the original toot instead of the booster :)

**Comment by Lertsenem** [comment]
Wow, you were so fast that I first thought "wow, how did I miss that option" ! But when testing it I realized I was a few versions late now! Thanks a lot for that. :)
