### ISSUE TITLE
Featurerequest: intelligent timeline switching

### ISSUE THREAD

**Issue by Glog78** [RasmusLindroth/tut#225]
Thanks again for all the hard work you put into tut. 

I have done my setup the following way:
```
leader-action=home,1
leader-action=local,2
leader-action=notifications,0
leader-action=federated,3
leader-action=saved,9
```

how ever there is something which i would love to avoid -> open everytime a new timeline but just switch to the timeline if it is already open and only open it once it is not already open.

From my mind i would see 2 possibilities ->

a.) Additional parameter to timelines in the config
example ->
```
timelines=notification,[N]otifications,'n','N',hidden=xx
```
this opens the timeline but instead of also open a window the window isn't shown but the number of the window is given in the background.  After i can bind a leader-action like leader-action=window xx,n to make this window shown.

b.) and i guess this is the better one something like
```
leader-action=switch home, 1
````
Which first check if a home timeline has already opened and switches to this timeline instead of creating a new timeline. If it isn't opened create a timeline like now.

Thank you again alot.

I guess my current config  https://termbin.com/0nl24  helps a little to understand the workflow i am aiming for.

**Comment by RasmusLindroth** [comment]
Great suggestion! I'll look into it and I also think the second approach seems better

**Comment by RasmusLindroth** [comment]
You now have `leader-action=switch feed,shortcut,[name],[showBoosts],[showReplies]` but it will open a new window if the feed doesn't exist instead of opening it in the current window

**Comment by Glog78** [comment]
in the example ini the following line is included
# leader-action=switch feed,shortcut,[name],[showBoosts],[showReplies]

i tried
lead-action=switch local,2,Local

this crashes:

```
switch is invalid . Check this for errors: switch local,"Local"
```

**Comment by RasmusLindroth** [comment]
Now it should be working as intended
