### ISSUE TITLE
boosted toot doesn't show content warning

### ISSUE THREAD

**Issue by shinenelson** [RasmusLindroth/tut#23]
A toot with a content warning, when boosted, does not show the content warning. It only shows the content of the toot. The content warning text is completely omitted from the boosted toot. Shouldn't it show the content warning for the toot ( and hide the content ) in the boosted toot as well?

![Screenshot from 2020-08-13 02-13-15_blurred](https://user-images.githubusercontent.com/4771718/90067210-61e58800-dd0c-11ea-942d-d99d769fbcce.png)
![Screenshot from 2020-08-13 02-31-32_blurred](https://user-images.githubusercontent.com/4771718/90067970-8857f300-dd0d-11ea-807c-f8f675b81d26.png)
![Screenshot from 2020-08-13 01-54-13_blurred](https://user-images.githubusercontent.com/4771718/90067200-5d20d400-dd0c-11ea-969d-929fa2c33273.png)

**Comment by RasmusLindroth** [comment]
Good catch, I will start working on a fix

**Comment by RasmusLindroth** [comment]
Fixed in https://github.com/RasmusLindroth/tut/commit/8ddd68c8f2538a08cef62ee03dc5aee56cedb366
