### ISSUE TITLE
possible issue with gotosocial?

### ISSUE THREAD

**Issue by r3k2** [RasmusLindroth/tut#235]
Hello, Happy Hoklidays
    Not 100% sure but maybe good to check since more and more instances are choosing to run GoToSocial, when running under TUT is super slow and I fail to see the whole local stream like with regular mastodon instances, At first I told the admin that maybe something is wrong in his instance but I also decided to download the mastodon client on my phone(I rarely use phones for anything, I use it more as a modem to have internet with my laptops anywhere) and there with the official mastodon app works like a charm, then I went back to TUT and same slowness and issues :( 
Happy Holidays BTW and thanks for creating this mastodon client I know tons of us really appreciate it. ❤️

**Comment by bronikowski** [comment]
I want to +1 it because I just went to issues to report that `tut` is constantly hammering two non-existing endpoints of gotosocial:

* `/api/v1/streaming/user`
* `/api/v1/streaming/public`

It produces lots and lots of 404s.

**Comment by RasmusLindroth** [comment]
It's because tut does streaming over https instead of websockets. I thought I already used websockets, so I'll try to create a new release tomorrow with support for it :)

**Comment by RasmusLindroth** [comment]
Now tut uses WebSockets, so hopefully it will work :)

Happy New Year!

**Comment by r3k2** [comment]
@RasmusLindroth Thank you! and Happy New year, I got home yesterday and it was working great, until I tried to boost another toot, then started to have issues.
