### ISSUE TITLE
Media not opening

### ISSUE THREAD

**Issue by jsanz** [RasmusLindroth/tut#237]
1.0.26 introduced an issue for me that remains until the last release. For some reason I can't open media files from `xdg-open` in Linux

```
image-viewer=xdg-open
```

On the following clip I check that the file in `/tmp/` is not present with the first configuration.

![Peek 2022-12-28 10-33](https://user-images.githubusercontent.com/188264/209790933-ad2ef5f3-6153-46b9-85f4-300bf5b001f1.gif)

On the other hand, I can open images with this other setting with `alacritty` and `chafa`, where the file is correctly placed in `/tmp`

```
image-viewer=alacritty -e chafa --watch
```

Any ideas what could be wrong?

**Comment by RasmusLindroth** [comment]
It must me that the file gets removed before the image viewer has finished, but tut should wait with the deletion of files till the image-viewer program has finished.  What program does `xdg-open` run when you open images? Is it part of maybe Gnome?

**Comment by jsanz** [comment]
`xdg-open` was using `eog` from Gnome, I changed to an alternative viewer ([`ristretto`](https://docs.xfce.org/apps/ristretto/start), from XFCE) and it works as expected.

I also changed `xdg-open` for the video player by `vlc` and it also works as expected so yeah, this seems to be some weird behavior from Gnome.

Closing, thanks for the suggestion!!

**Comment by Dronakurl** [comment]
Hi, I experience the same problem with 1.0.34. I didn't find a way to get the ~/.config/mimeapps.list such that ristretto opens. It always defaults to my default webbrowser google-chrome.

**Comment by jsanz** [comment]
Sharing my settings in case they are of any help

```text
[media]
image-viewer=ristretto
image-terminal=false
image-single=true
image-reverse=false

video-viewer=vlc
video-terminal=false
video-single=true
video-reverse=false
```

**Comment by RasmusLindroth** [comment]
> Hi, I experience the same problem with 1.0.34. xdg-open defaulted to google-chrome. It doesn't work with ristretto either. The file seems to be deleted. Any hints for me?

If you try the version `2.0.0` and set `delete-temp-files=false` under `[media]`. Can you open the image?

**Comment by Dronakurl** [comment]
Congratulations to Version 2.0.0!
Unfortunately: No
I tried jsanz settings, and also your settings, but somehow xdg-open doesn't use the 'image-viewer=ristretto' command in the '[media]' section but only the defaults under '[Default Applications]'.
I have xdg-open version 1.1.3

here is my .config/mimeapps.list
´´´
[Default Applications]                                                                                                                               
  text/html=google-chrome.desktop                                                                                                                      
  x-scheme-handler/http=google-chrome.desktop                                                                                                          
  x-scheme-handler/https=google-chrome.desktop                                                                                                         
  x-scheme-handler/about=google-chrome.desktop                                                                                                         
  x-scheme-handler/unknown=google-chrome.desktop                                                                                                       
  x-scheme-handler/mailto=xfce4-mail-reader.desktop                                                                                                    
                                                                                                                                                       
  [media]                                                                                                                                              
  delete-temp-files=false                                                                                                                              
  image-viewer=ristretto                                                                                                                               
  image-terminal=false                                                                                                                                 
  image-single=true                                                                                                                                    
  image-reverse=false                                                                                                                                  
  delete-temp-files=false
´´´
I could not find any support for a media section in the docs for xdg-open
https://specifications.freedesktop.org/mime-apps-spec/latest/
