### ISSUE TITLE
Get max_toot_chars from instance

### ISSUE THREAD

**Issue by omnivagant** [RasmusLindroth/tut#239]
Some implementations, like pleroma and glitch-soc, implement and show the client `max_toot_chars`. I'd suggest to try to use that if `char-limit` is not set, assuming there are other implementations and having `char-limit` configurable in `tut` would still be desirable.

Example of what the python client `toot` does: https://github.com/ihabunek/toot/blob/master/toot/tui/app.py#L320

**Comment by RasmusLindroth** [comment]
It's now fixed in the latest release :)
