### ISSUE TITLE
panic: runtime error: when favoriting toot from notifications view

### ISSUE THREAD

**Issue by shinenelson** [RasmusLindroth/tut#24]
attempting to favorite a toot from the `[N]otifications` view throws a `panic: runtime error`. However, the Favorite API request does go through. The toot would be favorited when I restart `tut` again.

### Steps to Reproduce
- Login to instance
- Press **`N`** to get into Notifications view
- Press **`F`** to Favorite first toot in notifications

### Expected Behavior
- toot is favorited
- action item changes from **`[F]avorite`** to **`Un[F]avorite`**
- `tut` does not crash

### Actual Behavior
- toot is favorited
- `tut` crashes
  <details>
  <summary>stack-trace</summary>

  ```
  panic: runtime error: index out of range [19] with length 15 [recovered]
	  panic: runtime error: index out of range [19] with length 15

  goroutine 1 [running]:
  github.com/rivo/tview.(*Application).Run.func1(0xc0002c2000)
	  $GOPATH/pkg/mod/github.com/rivo/tview@v0.0.0-20200712113419-c65badfc3d92/application.go:244 +0x82
  panic(0x8256e0, 0xc000019040)
	  $GOPATH/src/runtime/panic.go:967 +0x15d
  main.(*NotificationsFeed).Input(0xc000362000, 0xc00000e840)
	  $GOPATH/src/github.com/RasmusLindroth/tut/feed.go:1130 +0x45a
  main.(*StatusView).inputBoth(0xc0001302a0, 0xc00000e840)
	  $GOPATH/src/github.com/RasmusLindroth/tut/statusview.go:178 +0x8c
  main.(*StatusView).Input(0xc0001302a0, 0xc00000e840, 0xc0002c2000)
	  $GOPATH/src/github.com/RasmusLindroth/tut/statusview.go:268 +0x39
  main.main.func1(0xc00000e840, 0xc000273a28)
	  $GOPATH/src/github.com/RasmusLindroth/tut/main.go:251 +0x561
  github.com/rivo/tview.(*Application).Run(0xc0002c2000, 0x0, 0x0)
	  $GOPATH/pkg/mod/github.com/rivo/tview@v0.0.0-20200712113419-c65badfc3d92/application.go:314 +0x7d3
  main.main()
	  $GOPATH/src/github.com/RasmusLindroth/tut/main.go:294 +0xd34
  ```
  </details>

**Comment by RasmusLindroth** [comment]
Thank you for the issue and the stacktrace, I will look into it!

**Comment by RasmusLindroth** [comment]
Closed in https://github.com/RasmusLindroth/tut/commit/03e2373d845b52b625b661426fe390552c3a213c
