### ISSUE TITLE
Beta 2.0.0 bug

### ISSUE THREAD

**Issue by Glog78** [RasmusLindroth/tut#246]
with https://termbin.com/5p8b (config.toml) as config and https://termbin.com/w9y8 (gbddark.toml)

the following strange things happens ->
a.) the pane title inside of the window always stays at home
b.) left let me go throu the panes in one direction but right doesn't let me go throu the panes the other direction
c.) leader q doesn't close the current pane and switches to the one before or to an default one 

a nice addition would be terminal-tittle=3 (no terminal tittle  no top bar cause the panes work as top bar)

thank you for version 2.0.0 beta -> it's a big update and i love it (next will test the new editor , cause it seems char-limit is removed from the settings and my instance have 1024)

**Comment by RasmusLindroth** [comment]
a) Now it should update if the name is set
b) This should be fixed
c) `close-pane` doesn't close a timeline, so for it to work you'll have to have multiple panes

terminal-title=3 is now included
