### ISSUE TITLE
beta 2.0.0 bug

### ISSUE THREAD

**Issue by Glog78** [RasmusLindroth/tut#247]
if i use https://termbin.com/j0fg as config, i can switch panes with tab but i can't switch panes with left and right.

**Comment by RasmusLindroth** [comment]
I made a typo, so it should be `special-keys=["Right"]`. Thanks :)

**Comment by Glog78** [comment]
I am not sure if you fixed this one , i compiled 23a7d15a96f49916d93e8ce14a3820d4e6b89e51 from 2.0.0 branch. 

It seems like [input.main-prev-feed] and [input.main-next-feed] doesn't work with a setup as shown in the original config. What works in this case is disable left and right from those function and use them on [input.main-prev-pane] and [input.main-next-pane]

(aka i fixed it  with a config change on my side) but you might have a look once you have time maybe.

**Comment by RasmusLindroth** [comment]
But `h` or `Left arrow` and `l` and `Right arrow` should switch inside the pane and `Tab` or `Backtab` between panes, so it should be the behavior I intended. Or am I missing something?
