### ISSUE TITLE
Beta 2..0.0 bug

### ISSUE THREAD

**Issue by Glog78** [RasmusLindroth/tut#251]
used config:
[CONFIG.ZIP](https://github.com/RasmusLindroth/tut/files/10419274/CONFIG.ZIP)

steps to reproduce:

1.) open tut
2.) press 2 to have a the local timeline open too
3.) :tag #linux

result:
 a.) title of the pane doesn't change
 b.) the local pane is hidden 

expected:
 a.) title of pane should change form [2] local -> tag #linux 

awesome:
 b.) it would open a new pane instead of in the same pane (might be a config error on my side)

**Comment by RasmusLindroth** [comment]
Should be fixed. Added `dynamic-timeline-name` under general to fix your expected and `commands-in-new-pane` to fix the awesome one :)
