### ISSUE TITLE
Better formating for <ul> lists

### ISSUE THREAD

**Issue by Lertsenem** [RasmusLindroth/tut#252]
Some Fediverse software allow for a subset of HTML to format posts. While most of it renders okay in tut, `<ul>` lists rendering is pretty awful.

Here is a comparison between the web rendering and tut rendering of [this toot](https://mastodon.lertsenem.com/@lertsenem/109730749349645661):

![image](https://user-images.githubusercontent.com/1083508/213913563-bdaa6191-05ef-4363-9d9b-e665f08dc3e6.png)
![image](https://user-images.githubusercontent.com/1083508/213913571-3017ac57-bfee-489f-bd7c-de52b5a40959.png)

PS: it might be nice to have some indications for `<em>` and `<strong>` tags too.

**Comment by RasmusLindroth** [comment]
It's now in the 2.0.0 branch :)

![2023-01-22-150651](https://user-images.githubusercontent.com/10499481/213920070-b024f840-3961-4b7b-bb0f-82574bbb9d7e.png)

**Comment by Lertsenem** [comment]
Nice! As always I'm amazed by how fast you are to address those issues. Thank you! :D
