### ISSUE TITLE
Theme doesn't change via config

### ISSUE THREAD

**Issue by Ashdemai** [RasmusLindroth/tut#254]
After the recent update it changed back to the default theme. I tried changing it back with the new config.toml but it does nothing. Tried messing with naming, changing the default.toml in the themes/ folder, but nothing changes.

**Comment by RasmusLindroth** [comment]
You'll have to change the extension from `ini` to `toml`. And all colors must be surrounded by quotation marks as of toml.

Like this
`text="#ffffff"`

And in config.toml you shouldn't include the file extension.

It should work as others have gotten it to work. If you still have a problem you can post my your config and your theme and I'll have a look :)

**Comment by Ashdemai** [comment]
Yeah the quotation marks weren't added in my conversion.
