### ISSUE TITLE
xrdb colors not working

### ISSUE THREAD

**Issue by Lertsenem** [RasmusLindroth/tut#31]
For some reason, configuring the colors using xrdb codes does not work (hex codes and names work, though).

I'm using tut in xterm with a solarized light theme. Here's the relevant part of my .Xresources:

```
! Common

#define S_yellow        #b58900
#define S_orange        #cb4b16
#define S_red           #dc322f
#define S_magenta       #d33682
#define S_violet        #6c71c4
#define S_blue          #268bd2
#define S_cyan          #2aa198
#define S_green         #859900


! Light

#define S_base03        #002b36
#define S_base02        #073642
#define S_base01        #586e75
#define S_base00        #657b83
#define S_base0         #839496
#define S_base1         #93a1a1
#define S_base2         #eee8d5
#define S_base3         #fdf6e3

XTerm*background:              white
XTerm*foreground:              S_base00
XTerm*fading:                  40
XTerm*fadeColor:               S_base3
XTerm*cursorColor:             S_base01
XTerm*pointerColorBackground:  S_base1
XTerm*pointerColorForeground:  S_base01

XTerm*color0:                  S_base02
XTerm*color1:                  S_red
XTerm*color2:                  S_green
XTerm*color3:                  S_yellow
XTerm*color4:                  S_blue
XTerm*color5:                  S_magenta
XTerm*color6:                  S_cyan
XTerm*color7:                  S_base2
XTerm*color9:                  S_orange
XTerm*color8:                  S_base03
XTerm*color10:                 S_base01
XTerm*color11:                 S_base00
XTerm*color12:                 S_base0
XTerm*color13:                 S_violet
XTerm*color14:                 S_base1
XTerm*color15:                 S_base3
```

And here's what my tut looks like, side by side with the config file open in vim for comparison with the expected colors :

![tut](https://user-images.githubusercontent.com/1083508/113142775-94a4a800-922b-11eb-8e0c-449bca674753.png)

**Comment by RasmusLindroth** [comment]
Hi! That doesn't seem to be right. Could you please attach your config under the `[style]` section, you can find the file at `~/.config/tut/config.ini`

**Comment by RasmusLindroth** [comment]
> tut is basically unusable out of the box here also on Solarized. Would be really nice to have some built in themes.

Now tut has themes :)

**Comment by kflak** [comment]
Trying to add my own theme in .config/tut/themes/gruvbox.ini, but tut is complaining about not finding it. Where should I put the theme file for tut to find it?

**Comment by RasmusLindroth** [comment]
> Trying to add my own theme in .config/tut/themes/gruvbox.ini, but tut is complaining about not finding it. Where should I put the theme file for tut to find it?

As it is now you can't add your own themes like that. It has to come bundled with tut, so you'd have to submit a PR with your theme. But maybe it's a good idea that you could have your own local themes. I will look at it.
