### ISSUE TITLE
I think this is unfortunately dead

### ISSUE THREAD

**Issue by r3k2** [RasmusLindroth/tut#32]
I love the app, I love go and mastodon and the CLI. but creator seems inactive since September 2020 according to his profile, so that means in all his projects etc here in github... anyone willing to help me continue development on a fork or if he reads that he can add us as developers?
- will be nice to add some kind of image support even as ascii like gomuks(cli matrix client in go)
- also commit the PR that is waiting.
-  etc..

**Comment by RasmusLindroth** [comment]
I'm more than happy to give more people access to this project. So you'll not have to fork it.

I work as a teacher so it's mostly during the summer I have the time and feel motivated to work on bigger projects, but my plan is to give tut some love when this semester ends in June.

I'm glad so many likes this software, so if anyone wants to become a contributor they are welcome to contact me :)

**Comment by toxision** [comment]
But it's good to read at least a life-sign, regardless of how much effort you want to spend into tut.
Nevertheless just an FYI: it's still my daily driver since it is doing many things very correct imho. Keep it up 👍

Cheers,
Chris

**Comment by r3k2** [comment]
@RasmusLindroth Hello I just notice you reply to my msg, I got an email that a git repo issue was closed and usually I ignore them since most of the times is from old projects since I only use gitlab and sourcehut now a days, I am super happy you are going to get back in summer to update the project, if not I still can help, I do have less time now that I had when I wrote that but I can always find some time for this if needed. cheers
