### ISSUE TITLE
Key conflict in new version

### ISSUE THREAD

**Issue by nyex** [RasmusLindroth/tut#34]
Hey! I just tried using `s` to 'show' content in a toot with CW, as it was before (https://i.imgur.com/9LH0d5Z.png). But now `s` is too bookmark toot, it seems, so I can't view a toot with CW anymore. So I guess one of them needs to have a different shortcut? Or did you already change the shortcut to viewing full content and didn't change the 'tooltip'?

Cheers!

**Comment by RasmusLindroth** [comment]
Oh, clumsy of me. I will fix it during the day :)
