### ISSUE TITLE
[FR] Desktop notifications support?

### ISSUE THREAD

**Issue by kflak** [RasmusLindroth/tut#37]
Hi, and thanks for a great client! Really enjoying it so far.

Just wondering if there are any plans to add support for desktop notifications for those of us that enjoy those kinds of things? 
`notify-send blah` kind of thing...

**Comment by toxision** [comment]
haha I was thinking about the exact same thing. The notify-send is rather trivial and easy to implement. However I am not sure how complicated it can get, when chaining with Go implementations like this project here. I am not experienced enough in programming, so any hints are welcome :)

**Comment by RasmusLindroth** [comment]
Good suggestion. That shouldn't be that hard to implement. I'll have a look at it :)

**Comment by RasmusLindroth** [comment]
It will be included in the next release :)

**Comment by kflak** [comment]
Great!

--
Roosna & Flak - Contemporary Dance & Music
Web: roosnaflak.com
Code: {github,gitlab}.com/kflak
Mastodon: @***@***.***
