### ISSUE TITLE
Compond emijo don't don't clear properly

### ISSUE THREAD

**Issue by zethra** [RasmusLindroth/tut#38]
As you may know some emoji such as 💁🏻‍♀️ are actually made up of several characters but are meant to be rendered as 1. My terminal doesn't render these correctly as is fairly common instead rendering it as 3 separate characters.
![image](https://user-images.githubusercontent.com/6034238/125503122-906bb117-2c2e-4038-9002-737a7ecdcf10.png)
This rendering issue isn't a bug in tut. However, when scrolling to different toots those extra emoji don't clear properly until they're drawn over. 
![image](https://user-images.githubusercontent.com/6034238/125503566-92ddd1ad-2fb3-4ad4-af7a-3ca1c9d60bce.png)
IDK if this a a bug in tut, the tui library tut is using, or my terminal.

**Comment by toxision** [comment]
Hi zethra
Interesting you are mentioning that. I have exactly the same issue, but never really cared so far. Seems to be at least terminal emulator independent (happened in all I tried so far) and I am using bash under Linux Mint.

PS: I am not a developer myself and so, cannot look or analyze further 🤷🏼 

Cheers,
Chris

**Comment by RasmusLindroth** [comment]
I think this is related to this issue https://github.com/RasmusLindroth/tut/issues/38 in tview. I'll leave this issue open, so if anyone have any idea why it leaves artifacts and doesn't render properly can point out the problem.

Thank you for the issue, even though I'm clueless :)

**Comment by RasmusLindroth** [comment]
Fixed in the latest release
