### ISSUE TITLE
GLIBC_2.32

### ISSUE THREAD

**Issue by SlidingHorn** [RasmusLindroth/tut#39]
So between 0.0.17 and 0.0.18 it looks like there was an update that included a requirement for `GLIBC_2.32`

I'm just using the binaries on Ubuntu 20.04 - not sure exactly which library I'd need to install or if the one available is new enough. I can run 0.0.17 just fine, but 0.0.18 and 0.0.20 won't run do to this requirement.

**Comment by toxision** [comment]
@SlidingHorn 
Had the same issue on Linux Mint (Ubuntu based version)
Try the static binary ;)

**Comment by SlidingHorn** [comment]
> @SlidingHorn
> Had the same issue on Linux Mint (Ubuntu based version)
> Try the static binary ;)

That works!

Didn't even see that when I went to look for the binaries. Thanks!
