### ISSUE TITLE
Feature Request: Extend options in "Open" window

### ISSUE THREAD

**Issue by SlidingHorn** [RasmusLindroth/tut#40]
It would be great to have a couple more options to use to deal with the URLs in the "Open" window:

- Copy highlighted URL
- Open in a secondary browser (or another application/script treated as a browser)*

\* an example of this:  In `newsboat`, I can set a macro in my config file to temporarily set my "browser" to any command, and pass the URL through to that command.  Afterwards, I reset my browser back. Example:

`macro m set browser "/path/to/script"; open-in-browser ; set browser "/original/browser/path"`

I use this, for instance, to open youtube videos in `youtube-viewer`/mpv rather than opening a browser window to watch them on the website.

I understand that this is probably no small task to accomplish, so I just wanted to put the bug in your ear to see if it interests anyone.

**Comment by RasmusLindroth** [comment]
That seems useful. I'll have a look at it :)

**Comment by RasmusLindroth** [comment]
Thank you for the suggestions. You can read about the new features in the latest release https://github.com/RasmusLindroth/tut/releases/tag/0.0.21

**Comment by SlidingHorn** [comment]
That works great for me. Thanks!
