### ISSUE TITLE
Replies fail to render properly after loading overlay in notifications

### ISSUE THREAD

**Issue by justjosias** [RasmusLindroth/tut#43]
When replying to a post in the home timeline after loading the reply overlay for a toot in notifications, it displays the reply from notifications instead of the one from the home timeline.

Steps to reproduce:
1. Press `n` to enter the notifications timeline
2. Press `r` to reply to a message
3. Exit the reply modal with `esc` (or reply to a message, doesn't matter)
4. Exit the notifications timeline with `esc`
5. Reply to a message in the home timeline

Current workaround: open the notifications timeline and exit it again.

I'm guessing this problem is related to getting the current status and changing timelines.

**Comment by RasmusLindroth** [comment]
It should be fixed now. Thank you for the detailed bug report :)

**Comment by RasmusLindroth** [comment]
The bug fix wasn't that good. Now reading treads from notifications gets messed up instead.

**Comment by RasmusLindroth** [comment]
Should be fixed with commit c4373b2b8e60893a4ad791e9f4479111047d1532

**Comment by justjosias** [comment]
This issue has presented itself almost identically again in CWs. When one opens and closes the notifications timeline with a CW, the next CW in the home timeline is replaced with the one in the notifications timeline when opened.
