### ISSUE TITLE
Tut is showing poll results, even if not voted 

### ISSUE THREAD

**Issue by toxision** [RasmusLindroth/tut#51]
Hi
Although polls cannot be voted (yet? ;), you are always able to already see the results. I think this against the Mastodon philosophy to not let influence yourself by the already given votes. Not sure if it is technically possible to hide them before the person voted (currently with another client only)

Cheers,
Chris

**Comment by RasmusLindroth** [comment]
I almost never participate in polls, so I've almost forgot that you can't vote. Of course you should be able to vote so I'll look into it :)

Do you have any suggestion for key bindings?

**Comment by toxision** [comment]
> I almost never participate in polls, so I've almost forgot that you can't vote. Of course you should be able to vote so I'll look into it :)
> 
> Do you have any suggestion for key bindings?

Ohhh ehmm, I haven't meant the option to vote in general. Although this would be really awesome 🥳 
No, my intention was that usually, at least natively in browser and in mobile apps like Tusky, the results are not visible, until you have given your vote yourself. Tut however is always showing the current answered polls even so, the user profile has not voted yet.

**Comment by RasmusLindroth** [comment]
Now it's all implemented :)
