### ISSUE TITLE
Custom keybindings?

### ISSUE THREAD

**Issue by kflak** [RasmusLindroth/tut#53]
As I develop muscle memory for tut, my mutt muscle memory is deteriorating, so that I start pressing 'P' for sending a mail, which postpones it instead. So I was wondering if there is any way to customize the keycommands in the configuration file? Or if this is a hugely complicated thing to implement?

**Comment by RasmusLindroth** [comment]
Good suggestion. It should't be that complicated, but I'll have to think about how to solve conflicts when reusing the same key in different views.

**Comment by skyfaller** [comment]
Relatedly, but perhaps belonging in its own issue, can we get full documentation of the current keys? I somehow hit a sequence of keys that unfollowed someone, which was slightly more annoying because they require follow requests, so I had to bother them. I cannot figure out what the key sequence I hit was.

**Comment by jb55** [comment]
yeah current keys are a bit awkward. I keep hitting the B key when trying to go to notifications, unwittingly boosting random toots

**Comment by brunofontes** [comment]
That would really be awesome to have. Every now and then I press the letter "q" to go back from somewhere and end up closing a timeline or even tut itself. So it would be great to setup it in a way that were not possible to close the app or timelines by just pressing a single letter.

**Comment by RasmusLindroth** [comment]
Now tut support custom keys, so checkout the latest release :)

**Comment by kflak** [comment]
Thank you!
