### ISSUE TITLE
Can't follow user

### ISSUE THREAD

**Issue by kflak** [RasmusLindroth/tut#54]
I may just have missed something, but when I open a user and hit [F] for follow, nothing happens... Same thing with [A]vatar, [B]lock and [M]ute.

Platform: Arch Linux, tut v 0.0.26

**Comment by RasmusLindroth** [comment]
Is it the same on all users you or is it just on some users? Can you see any error message?

Unfortunately I'm unable to reproduce the bug.

**Comment by kflak** [comment]
It seems to be the same across all users, as far as I can tell... And no error message either. Just no response whatsoever. Any tips on how I can help to narrow down the problem?

**Comment by RasmusLindroth** [comment]
Dit it work with previous versions? If so, could you try an older version?
What instance are you on?
Did you install it through AUR?

Thank you for helping with the troubleshooting

**Comment by kflak** [comment]
Hi, I installed via aur. I did a clean reinstall, removing cache etc., and now it seems to work fine again! Hmmmm...
