### ISSUE TITLE
Unsupported characters keep showing up

### ISSUE THREAD

**Issue by davidoskky** [RasmusLindroth/tut#56]
Certain statuses can contain characters or emojis which are not correctly displayed.
These characters don't disappear in the right pane when switching to another toot.
You therefore can read the new toot, but with strange symbols sparkled here and there.

You can check this toot for reference: https://mastodon.uno/@mte90/106766305830855593
it has two of those characters in the name and one in the text.

**Comment by RasmusLindroth** [comment]
I think it's the same problem as in this issue. Unfortunately I don't know how to fix it https://github.com/RasmusLindroth/tut/issues/38
