### ISSUE TITLE
Feature Request: Show favourited toots

### ISSUE THREAD

**Issue by haary** [RasmusLindroth/tut#64]
There seems to be no way to show the toots which were favourited. OTOH the :bookmarks and the :saved commands seem to be doing the same thing (showing bookmarked toots).

**Comment by RasmusLindroth** [comment]
Thank you for the suggestion. It's now included :)

https://github.com/RasmusLindroth/tut/releases/tag/0.0.29

**Comment by haary** [comment]
Great, thank you very much :)
