### ISSUE TITLE
[Request] Open multiple media files in reverse...

### ISSUE THREAD

**Issue by SlidingHorn** [RasmusLindroth/tut#65]
This may sound stupid, but hear me out:

* Someone posts a toot of, say, a 4-panel comic with the images in order from 1-4,
* A tiling window manager user opens said media in an external application
* Image 4 is shown until you close it, then 3, then 2, then 1

This is, at least, the behavior in i3. I don't know if this is the same in *all* tiling WMs

I did notice that when I used MATE, it would open them 1-4 so that 4 - being opened last - was on top and 1 on the bottom of the stack, so maybe it's a universal thing....I don't know.

Anyway, would opening them in reverse be a possibility?

**Comment by toxision** [comment]
Oh not stupid at all. I never thought of the order, but you're right. Just tested it with Mate DE and it happens in the same order. So the last image is always presented first, then second last etc....

**Comment by RasmusLindroth** [comment]
Thank you for the suggestion. It's now included :)

https://github.com/RasmusLindroth/tut/releases/tag/0.0.29
