### ISSUE TITLE
Help text at bottom not appearing correctly.

### ISSUE THREAD

**Issue by klundry** [RasmusLindroth/tut#66]
[IMG_20210829_110323](https://user-images.githubusercontent.com/15848724/131255244-1bfd3055-7b5f-47be-8882-7aa17399a2f6.jpg)

Before the shortcut letter between the brackets it shows like this [#-00001]

**Comment by RasmusLindroth** [comment]
What terminal are you using? And have you changed something in the `[style]` section of your config?

**Comment by klundry** [comment]
Hmmm, when launching it today the problem is gone. This is using Qterminal and I have not changed anything in the config file. Not sure what changed for this to disappear. Maybe a reboot did it, but I'm almost certain I rebooted while trying to figure out why it was happening. Sorry.

**Comment by RasmusLindroth** [comment]
It's magical how a reboot can solve almost everything!

Just reopen this issue if it occurs again :)
