### ISSUE TITLE
[O]pen doesnt show URL from Non-Mastodon Activitypub instance toot

### ISSUE THREAD

**Issue by haary** [RasmusLindroth/tut#72]
When showing a posting ("a toot")  and pressing "o" a window opens from where a list of URLs and hashtags is shown. The user can no hit "o" again while on the URL and a web browser opens.

This is not working when the message originated from a non-Mastodon Activitypub instance, e g. from  https://connos.ddnss.ch/ (which is running "Honk" from  https://humungus.tedunangst.com/r/honk)

Steps to reproduce:

1. In Mastodon Web subscribe to an account from connos.ddnss.ch
2. In tut open a message from that account and press 'o'
3. The window opens, but no URL is shown, although there is an URL present in the message.

**Comment by RasmusLindroth** [comment]
Fixed by @davidoskky. Thank you for the issue :)

**Comment by RasmusLindroth** [comment]
Reopen because of https://github.com/RasmusLindroth/tut/pull/75#issuecomment-917885145

**Comment by RasmusLindroth** [comment]
Merged and a thank you to @davidoskky
