### ISSUE TITLE
Optimize for long screens

### ISSUE THREAD

**Issue by DhruvaSambrani** [RasmusLindroth/tut#73]
Thanks for such an awesome app.

I don't know if this is worth the time, but you could optimize for long screens by placing the List section above the main Post section

I did this for neix, and basically involved setting the height, width and position of the sections depending on the number of columns.

This would benefit those on Termux or such set ups.

**Comment by toxision** [comment]
Just the other day I thought about the exact same. So +1 😁

**Comment by RasmusLindroth** [comment]
Great idea! It's now included in the latest release :)
