### ISSUE TITLE
Show if a toot is part of a thread

### ISSUE THREAD

**Issue by davidoskky** [RasmusLindroth/tut#77]
It would be nice to display if one particular toot in the timeline is part of a thread, therefore if it has replies or it is a reply to another toot.
In this way you could immediately know if pressing the thread button will actually be useful, and not waste time checking the thread of single toots.

I used Tusky which doesn't provide this functionality, however from the web interface it's possible to infer this information as at least the number of replies is shown.

**Comment by RasmusLindroth** [comment]
Fixed in the latest release. Thank you for the idea :)
