### ISSUE TITLE
Breaking lines in CoolRetroTerm

### ISSUE THREAD

**Issue by drequivalent** [RasmusLindroth/tut#81]
Subj. When started in CRT, the client looks like this
![Снимок экрана от 2021-09-16 21-17-54](https://user-images.githubusercontent.com/1463277/133664572-b8c9af28-6b60-407a-ae81-4364468b1301.png)

Otherwise, great client!

**Comment by RasmusLindroth** [comment]
Except for the bug with the line it looks cool! But I'm afraid there's not much I can do about it. I think CoolRetroTerm is at fault here https://github.com/Swordfish90/cool-retro-term/issues/501
