### ISSUE TITLE
Use <tab> to select file path for media attachment

### ISSUE THREAD

**Issue by kflak** [RasmusLindroth/tut#83]
Hi,

When attaching a media file and hit `<tab>`, the file path is populated with the first thing that matches the letters I have typed. It would be very nice if it would stop before the next divergent character instead.

For example: if I have a filepath called `/home/me/abcccc` and `/home/me/abdddd`, and I type `/home/me/a<tab>`, the completion will be `/home/me/abccc`, instead of `/home/me/ab`, which would allow me to continue refining the path until I hit the one I want. It is possible to use the arrows after the fact to scroll up and down in the file list, but this is nowhere near as efficient as the behavior I'm looking for.

**Comment by RasmusLindroth** [comment]
This seems like a more resonable behavior. I'll have a look at it and it shouldn't be that hard to fix it :)

**Comment by RasmusLindroth** [comment]
Should be fixed with https://github.com/RasmusLindroth/tut/pull/85.

I'll include it in the next release which should be soonish

**Comment by kflak** [comment]
Awesome, thanks!

**Comment by RasmusLindroth** [comment]
Merged!
