### ISSUE TITLE
Creating or replying a toot withdraws part of the top-bar-background

### ISSUE THREAD

**Issue by toxision** [RasmusLindroth/tut#84]
Glitch only, considered as minor issue

Since the second last update or so, I am facing this graphical glitch. When replying to a toot or creating a new one, the left part of the top-bar-background is replaced with the default background color.
![Screenshot at 2021-09-26 12-22-33](https://user-images.githubusercontent.com/71572691/134805421-b2e34c48-dd6e-4555-940e-3f14c616505d.png)
 
But when I resize the window, everything looks just as normal as always. This happens regardless of the used terminal emulator software. However I am only using bash and so cannot say, if it happens with other shells as well.

BR,
Chris

**Comment by RasmusLindroth** [comment]
Thank you for the bug report. I've found a way to solve it by force redrawing the screen and by using this method I can solve the issue with artifacts from previous toots (https://github.com/RasmusLindroth/tut/issues/38).

I'll push a fix for this after I'd some time to test it :)

**Comment by RasmusLindroth** [comment]
Merged :)
