### ISSUE TITLE
auto update not working

### ISSUE THREAD

**Issue by r3k2** [RasmusLindroth/tut#94]
Im not sure when but from a couple weeks at least of maybe months my feed does not auto update even when I leave the first msg selected like it used to, I hate when I have to manually scroll up.. is a waste of time. did something changed?

**Comment by RasmusLindroth** [comment]
Hm, no it should work. It still works for me. 

Do you have `auto-load-newer=true` in your config and `auto-load-seconds=60` under `[general]`
