### ISSUE TITLE
Mouse Support

### ISSUE THREAD

**Issue by earboxer** [RasmusLindroth/tut#97]
It should be possible to use the mouse in this application.

* Touching the different panes should automatically switch between List, Notifications, and View modes
* It should be possible to select different entries in the List and Notifications panes by touching them

**Comment by klundry** [comment]
If you ever reconsider this feature I would also find it useful. For example I use tut on my Pinephone and i can scroll up and down with gestures but I have to open the on screen keyboard to change between the timeline and notification lists. It would be quite useful to be able to tap on the list that I want to be active. I don't think this would effect the vim-ness. Someone not wanting to use the mouse would never know the difference. Maybe it could even be toggled in the config?

**Comment by RasmusLindroth** [comment]
I changed my mind and implemented this feature in the latest release :)

**Comment by RasmusLindroth** [comment]
You'll have to set `mouse-support=true` under `[general]` in your config

**Comment by klundry** [comment]
Woohoo! Thanks so much.
