### ISSUE TITLE
name collision with package on Manjaro ARM

### ISSUE THREAD

**Issue by skyfaller** [RasmusLindroth/tut#99]
I am running Manjaro ARM Linux on the Pinebook Pro.

Every time I run yay to update my computer, I get this warning:
```
warning: tut: local (0.0.35-1) is newer than community (0.0.4-2)
```
It appears that there is an unrelated package that is a "C++ unit test framework" which is causing this name collision.

![20211025_15h39m26s_grim](https://user-images.githubusercontent.com/80093/138760153-41a3030c-2864-4e21-9ce9-c9e750907a1e.png)

Is there anything we could do to get rid of this warning? Is it worth considering renaming the Arch package to something else? Weirdly this package doesn't show up on the Arch Linux website under the colliding name, perhaps it is only a Manjaro thing.

**Comment by RasmusLindroth** [comment]
You can now use `aur/tut-mastodon`. I suggest you make an alias in your shell for it so you can use it as before. Change `.bashrc` or `.zshrc` and add `alias tut='tut-mastodon'`

https://aur.archlinux.org/packages/tut-mastodon/
